version: "3.9"
services:
  service_uni_user_db:
    image: postgres:12
    container_name: "service_uni_user_db"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - service-uni-network

  service_uni_pgadmin:
    image: dpage/pgadmin4
    container_name: service_uni_pgadmin
    depends_on:
      - service_uni_user_db
    ports:
      - "5051:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - service-uni-network
    restart: always

  service_uni_user_api:
    container_name: "service_uni_user_api"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "service_uni_user_db"
    ports:
      - "8001:8001"
    restart: always
    networks:
      - service-uni-network

networks:
  service-uni-network:
    external: true