# Generated by Django 4.2.5 on 2023-09-26 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='school',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='current_course_handling',
        ),
        migrations.RemoveField(
            model_name='serviceuser',
            name='current_enrolled_courses',
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='institution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='program',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='school',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='current_course_handling',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='current_enrolled_courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
