# Generated by Django 4.2.5 on 2023-10-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0003_alter_serviceuser_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceuser',
            old_name='institution',
            new_name='institution_id',
        ),
        migrations.RenameField(
            model_name='serviceuser',
            old_name='program',
            new_name='program_id',
        ),
        migrations.RenameField(
            model_name='serviceuser',
            old_name='school',
            new_name='school_id',
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='contact_phone',
            field=models.ManyToManyField(blank=True, to='service_user.phonecontact'),
        ),
    ]
