# Generated by Django 4.2.5 on 2023-10-04 22:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0004_rename_institution_serviceuser_institution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='current_course_handling',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
