# Generated by Django 4.2.5 on 2023-10-04 23:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0005_alter_serviceuser_current_course_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='current_course_handling',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
