# Generated by Django 4.2.5 on 2023-10-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0008_alter_serviceuser_current_course_handling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='date_of_birth',
        ),
    ]
