# Generated by Django 4.2.5 on 2023-10-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0009_remove_serviceuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
