# Generated by Django 4.2.5 on 2023-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0010_serviceuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceuser',
            name='student_status',
            field=models.CharField(blank=True, choices=[('FUTURE_STUDENT', 'FUTURE_STUDENT'), ('CURRENT_STUDENT', 'CURRENT_STUDENT'), ('GRADUATE', 'GRADUATE'), ('DENIED', 'DENIED')], max_length=16, null=True),
        ),
    ]
