# Generated by Django 4.2.5 on 2023-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0011_alter_serviceuser_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='program_approval',
            field=models.BooleanField(default=False),
        ),
    ]
