# Generated by Django 4.2.5 on 2023-10-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_user', '0012_serviceuser_program_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='soft_approval',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=8, null=True),
        ),
    ]
