# Generated by Django 4.2.5 on 2023-10-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_remove_subject_slug_institution_current_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='admin_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
