version: "3.9"
services:
  service_uni_api_gateway:
    container_name: "service_uni_api_gateway"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - service-uni-network

networks:
  service-uni-network:
    external: true